-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 22:16:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poule` DEFAULT CHARACTER SET utf8 ;
USE `poule` ;

-- -----------------------------------------------------
-- Table `poule`.`tijdstip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poule`.`tijdstip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poule`.`landen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poule`.`landen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poule`.`winnaar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poule`.`winnaar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poule`.`uitslag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poule`.`uitslag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goals_land_1` VARCHAR(45) NULL,
  `goals_land_2` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poule`.`wedstrijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poule`.`wedstrijd` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `land_1` VARCHAR(45) NULL,
  `land_2` VARCHAR(45) NULL,
  `tijdstip_id` INT NOT NULL,
  `winnaar_id` INT NOT NULL,
  `uitslag_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tijdstip_id`, `winnaar_id`, `uitslag_id`),
  INDEX `fk_team2_tijdstip1_idx` (`tijdstip_id` ASC),
  INDEX `fk_wedstrijd_winnaar1_idx` (`winnaar_id` ASC),
  INDEX `fk_wedstrijd_uitslag1_idx` (`uitslag_id` ASC),
  CONSTRAINT `fk_team2_tijdstip1`
    FOREIGN KEY (`tijdstip_id`)
    REFERENCES `poule`.`tijdstip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wedstrijd_winnaar1`
    FOREIGN KEY (`winnaar_id`)
    REFERENCES `poule`.`winnaar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wedstrijd_uitslag1`
    FOREIGN KEY (`uitslag_id`)
    REFERENCES `poule`.`uitslag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poule`.`wedstrijd_has_landen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poule`.`wedstrijd_has_landen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wedstrijd_id` INT NOT NULL,
  `landen_id` INT NOT NULL,
  PRIMARY KEY (`id`, `wedstrijd_id`, `landen_id`),
  INDEX `fk_wedstrijd_has_landen_landen1_idx` (`landen_id` ASC),
  INDEX `fk_wedstrijd_has_landen_wedstrijd1_idx` (`wedstrijd_id` ASC),
  CONSTRAINT `fk_wedstrijd_has_landen_wedstrijd1`
    FOREIGN KEY (`wedstrijd_id`)
    REFERENCES `poule`.`wedstrijd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wedstrijd_has_landen_landen1`
    FOREIGN KEY (`landen_id`)
    REFERENCES `poule`.`landen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
